---
version: 3

output: group

vars:
  WEB_COLOR: '#41403e'
  DOCKER_IMAGE_SKILLS: alistaircol/skills
  DOCKER_IMAGE_GRAPHVIZ: dot
  DOCKER_RUN: docker run --rm --tty --volume="$(pwd):/app" --workdir="/app" --user=$(id -u):$(id -g)
  DOCKER_RUN_SKILLS: "{{.DOCKER_RUN}} {{.DOCKER_IMAGE_SKILLS}}"
  SUBGRAPHS: |
    environment
    devops
    ssg
    servers
    proxies
    db
    queues
    cloud
    php
    css
    js
    misc
    concepts

tasks:
  lint:
    cmds:
    - "{{.DOCKER_RUN}} {{.DOCKER_IMAGE_YAMLLINT}} ."
    interactive: true

  default:
    cmds:
    - task: docker_pull
    - task: build_dot_image
    - task: clean
    - task: build_dot
    - task: build_png
    - task: build_svg
    - task: build_pdf

  docker_pull:
    cmds:
    - docker pull --quiet mnuessler/pdftk
    - docker pull --quiet cytopia/yamllint:latest

  build_dot_image:
    cmds:
    - BUILDKIT_PROGRESS=plain docker build --quiet --tag={{.DOCKER_IMAGE_SKILLS}} .
    interactive: true

  clean:
    cmds:
    - echo "TODO"s
    - find "$(pwd)/build" -type f -not -name ".gitkeep" -not -name "README.md" -delete
    - find "$(pwd)/dot" -type f -not -name "README.md" -delete
    interactive: true

  build_dot:
    cmds:
    - bash bin/build-primary.sh
    - bash bin/build-secondary.sh

  build_png:
    cmds:
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/skills.png dot/skills.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/skills-web.png dot/skills.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/environment.png dot/environment.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/environment-web.png dot/environment.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/devops.png dot/devops.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/devops-web.png dot/devops.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/ssg.png dot/ssg.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/ssg-web.png dot/ssg.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/servers.png dot/servers.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/servers-web.png dot/servers.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/proxies.png dot/proxies.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/proxies-web.png dot/proxies.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/db.png dot/db.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/db-web.png dot/db.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/queues.png dot/queues.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/queues-web.png dot/queues.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/cloud.png dot/cloud.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/cloud-web.png dot/cloud.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/php.png dot/php.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/php-web.png dot/php.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/css.png dot/css.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/css-web.png dot/css.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/js.png dot/js.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/js-web.png dot/js.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/misc.png dot/misc.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/misc-web.png dot/misc.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/concepts.png dot/concepts.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/concepts-web.png dot/concepts.dot"

  build_svg:
    cmds:
    - "{{.DOCKER_RUN_SKILLS}} dot -Tsvg -o build/skills.svg dot/skills.dot"

  build_pdf:
    cmds:
    - "{{.DOCKER_RUN_SKILLS}} dot -Tps2 -o build/skills.ps dot/skills.dot"
    - "{{.DOCKER_RUN_SKILLS}} ps2pdf build/skills.ps build/skills.pdf"
    - rm build/skills.ps
    - bash bin/canonicalise-pdf-skills.sh
