---
version: 3

output: group

vars:
  WEB_COLOR: '#41403e'
  DOCKER_IMAGE_SKILLS: alistaircol/skills
  DOCKER_IMAGE_GRAPHVIZ: dot
  DOCKER_RUN: docker run --rm --tty --volume="$(pwd):/app" --workdir="/app"
  DOCKER_RUN_SKILLS: "{{.DOCKER_RUN}} {{.DOCKER_IMAGE_SKILLS}}"

tasks:
  lint:
    cmds:
    - "{{.DOCKER_RUN}} {{.DOCKER_IMAGE_YAMLLINT}} ."
    interactive: true

  default:
    cmds:
    - task: docker_pull
    - task: build_dot_image
    - task: clean
    - task: build_dot
    - task: build_png
    - task: build_svg
    - task: build_pdf

  docker_pull:
    cmds:
    - docker pull --quiet mnuessler/pdftk
    - docker pull --quiet cytopia/yamllint:latest

  build_dot_image:
    cmds:
    - BUILDKIT_PROGRESS=plain docker build --quiet --tag={{.DOCKER_IMAGE_SKILLS}} .
    interactive: true

  clean:
    cmds:
    - find "$(pwd)/build" -type f -not -name ".gitkeep" -not -name "README.md" -delete
    - find "$(pwd)/bin" -type f -not -name "README.md" -delete
    interactive: true

  build_dot:
    cmds:
    - bash build-primary.sh
    - bash build-secondary.sh

  build_png:
    cmds:
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/skills.png bin/skills.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/skills-web.png bin/skills.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/environment.png bin/environment.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/environment-web.png bin/environment.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/devops.png bin/devops.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/devops-web.png bin/devops.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/ssg.png bin/ssg.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/ssg-web.png bin/ssg.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/servers.png bin/servers.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/servers-web.png bin/servers.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/proxies.png bin/proxies.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/proxies-web.png bin/proxies.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/db.png bin/db.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/db-web.png bin/db.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/queues.png bin/queues.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/queues-web.png bin/queues.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/cloud.png bin/cloud.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/cloud-web.png bin/cloud.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/php.png bin/php.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/php-web.png bin/php.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/css.png bin/css.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/css-web.png bin/css.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/js.png bin/js.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/js-web.png bin/js.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/misc.png bin/misc.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/misc-web.png bin/misc.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"transparent\" -o build/subgraphs/concepts.png bin/concepts.dot"
    - "{{.DOCKER_RUN_SKILLS}} dot -Tpng -Gbgcolor=\"{{.WEB_COLOR}}\" -o build/subgraphs/concepts-web.png bin/concepts.dot"

  build_svg:
    cmds:
    - "{{.DOCKER_RUN_SKILLS}} dot -Tsvg -o build/skills.svg bin/skills.dot"

  build_pdf:
    cmds:
    - "{{.DOCKER_RUN_SKILLS}} dot -Tps2 -o build/skills.ps bin/skills.dot"
    - "{{.DOCKER_RUN_SKILLS}} ps2pdf build/skills.ps build/skills.pdf"
    - rm build/skills.ps
    - bash canonicalise-pdf-skills.sh
